export const navLinks = [
  {
    id: 0,
    label: "Home",
    href: "/",
  },
];

export const categoryItems = [
  {
    name: "Real Estate",
    slug: "real-estate",
    icon: "https://eva.osclass-pro.ru/oc-content/themes/eva/img/4.png",
  },
  {
    name: "Sales",
    slug: "sales",
    icon: "https://eva.osclass-pro.ru/oc-content/themes/eva/img/1.png",
  },
  {
    name: "Jobs",
    slug: "jobs",
    icon: "https://eva.osclass-pro.ru/oc-content/themes/eva/img/8.png",
  },
  {
    name: "Education",
    slug: "education",
    icon: "https://eva.osclass-pro.ru/oc-content/themes/eva/img/3.png",
  },
  {
    name: "Dating",
    slug: "dating",
    icon: "https://eva.osclass-pro.ru/oc-content/themes/eva/img/7.png",
  },
];

export const states = [
  { value: "all", name: "All States" },
  { value: "AL", name: "Alabama" },
  { value: "AK", name: "Alaska" },
  { value: "AZ", name: "Arizona" },
  { value: "AR", name: "Arkansas" },
  { value: "CA", name: "California" },
  { value: "CO", name: "Colorado" },
  { value: "CT", name: "Connecticut" },
  { value: "DE", name: "Delaware" },
  { value: "FL", name: "Florida" },
  { value: "GA", name: "Georgia" },
  { value: "HI", name: "Hawaii" },
  { value: "ID", name: "Idaho" },
  { value: "IL", name: "Illinois" },
  { value: "IN", name: "Indiana" },
  { value: "IA", name: "Iowa" },
  { value: "KS", name: "Kansas" },
  { value: "KY", name: "Kentucky" },
  { value: "LA", name: "Louisiana" },
  { value: "ME", name: "Maine" },
  { value: "MD", name: "Maryland" },
  { value: "MA", name: "Massachusetts" },
  { value: "MI", name: "Michigan" },
  { value: "MN", name: "Minnesota" },
  { value: "MS", name: "Mississippi" },
  { value: "MO", name: "Missouri" },
  { value: "MT", name: "Montana" },
  { value: "NE", name: "Nebraska" },
  { value: "NV", name: "Nevada" },
  { value: "NH", name: "New Hampshire" },
  { value: "NJ", name: "New Jersey" },
  { value: "NM", name: "New Mexico" },
  { value: "NY", name: "New York" },
  { value: "NC", name: "North Carolina" },
  { value: "ND", name: "North Dakota" },
  { value: "OH", name: "Ohio" },
  { value: "OK", name: "Oklahoma" },
  { value: "OR", name: "Oregon" },
  { value: "PA", name: "Pennsylvania" },
  { value: "RI", name: "Rhode Island" },
  { value: "SC", name: "South Carolina" },
  { value: "SD", name: "South Dakota" },
  { value: "TN", name: "Tennessee" },
  { value: "TX", name: "Texas" },
  { value: "UT", name: "Utah" },
  { value: "VT", name: "Vermont" },
  { value: "VA", name: "Virginia" },
  { value: "WA", name: "Washington" },
  { value: "WV", name: "West Virginia" },
  { value: "WI", name: "Wisconsin" },
  { value: "WY", name: "Wyoming" },
];
export const fakedata = [
  {
    id: 0,
    isPremium: true,
    title: "Продажа квартиры в центре города",
    description:
      "Просторная квартира с отличным видом, расположенная в самом центре города. Идеальный вариант для тех, кто ценит комфорт и удобство.",
    state: "California",
    city: "Los Angeles",
    address: "8123 W Devon Ave",
    amount: 250,
    image: ["https://eva.osclass-pro.ru/oc-content/uploads/0/17_preview.jpg"],
    phoneNumber: "+18478468245",
    createdUserId: "",
    views: 43,
    createdAt: new Date(),
    category: "real-estate",
    subcategory: "Недвижимость",
  },
  {
    id: 1,
    isPremium: true,
    title: "Продажа дома на берегу океана",
    description:
      "Уютный дом с прекрасным видом на океан. Идеальное место для жизни и отдыха.",
    state: "California",
    city: "Los Angeles",
    address: "123 Ocean Blvd",
    amount: 500,
    image: ["https://eva.osclass-pro.ru/oc-content/uploads/0/17_preview.jpg"],
    phoneNumber: "+18478468245",
    createdUserId: "",
    views: 78,
    createdAt: new Date(),
    category: "real-estate",
    subcategory: "Недвижимость",
  },
  {
    id: 2,
    isPremium: true,
    title: "Продажа земельного участка",
    description:
      "Земельный участок с отличным расположением и потрясающими видами. Идеальный выбор для строительства вашего дома.",
    state: "California",
    city: "Los Angeles",
    address: "456 Main St",
    amount: 150,
    image: ["https://eva.osclass-pro.ru/oc-content/uploads/0/17_preview.jpg"],
    phoneNumber: "+18478468245",
    createdUserId: "",
    views: 65,
    createdAt: new Date(),
    category: "real-estate",
    subcategory: "Недвижимость",
  },
  {
    id: 3,
    isPremium: true,
    title: "Скидка на электронику",
    description:
      "Уникальная возможность приобрести современную электронику по выгодным ценам. Только сейчас со скидкой до 50%!",
    state: "California",
    city: "Los Angeles",
    address: "123 Main St",
    amount: 1000,
    image: ["https://eva.osclass-pro.ru/oc-content/uploads/0/17_preview.jpg"],
    phoneNumber: "+18478468245",
    createdUserId: "",
    views: 56,
    createdAt: new Date(),
    category: "sales",
    subcategory: "Продажи",
  },
  {
    id: 4,
    isPremium: true,
    title: "Распродажа мебели",
    description:
      "Большой выбор мебели по сниженным ценам. Не упустите свой шанс обновить интерьер своего дома!",
    state: "California",
    city: "Los Angeles",
    address: "456 Oak St",
    amount: 200,
    image: ["https://eva.osclass-pro.ru/oc-content/uploads/0/17_preview.jpg"],
    phoneNumber: "+18478468245",
    createdUserId: "",
    views: 32,
    createdAt: new Date(),
    category: "sales",
    subcategory: "Продажи",
  },
  {
    id: 5,
    isPremium: true,
    title: "Скидка на бытовую технику",
    description:
      "Большой выбор бытовой техники по сниженным ценам. Успейте приобрести себе новый холодильник или стиральную машину!",
    state: "California",
    city: "Los Angeles",
    address: "789 Elm St",
    amount: 300,
    image: ["https://eva.osclass-pro.ru/oc-content/uploads/0/17_preview.jpg"],
    phoneNumber: "+18478468245",
    createdUserId: "",
    views: 44,
    createdAt: new Date(),
    category: "sales",
    subcategory: "Продажи",
  },
  {
    id: 6,
    isPremium: true,
    title: "Вакансия: Программист",
    description:
      "Ищем опытного программиста для работы в нашей компании. Отличная зарплата и возможности для профессионального развития!",
    state: "California",
    city: "Los Angeles",
    address: "456 Oak St",
    amount: 70,
    image: ["https://eva.osclass-pro.ru/oc-content/uploads/0/17_preview.jpg"],
    phoneNumber: "+18478468245",
    createdUserId: "",
    views: 72,
    createdAt: new Date(),
    category: "jobs",
    subcategory: "Работа",
  },
  {
    id: 7,
    isPremium: true,
    title: "Вакансия: Дизайнер",
    description:
      "Требуется талантливый дизайнер для работы над интересными проектами. Присоединяйтесь к нашей команде уже сегодня!",
    state: "California",
    city: "Los Angeles",
    address: "789 Elm St",
    amount: 600,
    image: ["https://eva.osclass-pro.ru/oc-content/uploads/0/17_preview.jpg"],
    phoneNumber: "+18478468245",
    createdUserId: "",
    views: 39,
    createdAt: new Date(),
    category: "jobs",
    subcategory: "Работа",
  },
  {
    id: 8,
    isPremium: true,
    title: "Вакансия: Менеджер по продажам",
    description:
      "Ищем активного и коммуникабельного менеджера для работы в нашей команде. Опыт работы приветствуется!",
    state: "California",
    city: "Los Angeles",
    address: "101 Maple St",
    amount: 500,
    image: ["https://eva.osclass-pro.ru/oc-content/uploads/0/17_preview.jpg"],
    phoneNumber: "+18478468245",
    createdUserId: "",
    views: 27,
    createdAt: new Date(),
    category: "jobs",
    subcategory: "Работа",
  },
  {
    id: 9,
    isPremium: true,
    title: "Курсы английского языка",
    description:
      "Хотите выучить английский язык быстро и эффективно? Присоединяйтесь к нашим курсам, ведь знание языка — ключ к успеху!",
    state: "California",
    city: "Los Angeles",
    address: "789 Elm St",
    amount: 500,
    image: ["https://eva.osclass-pro.ru/oc-content/uploads/0/17_preview.jpg"],
    phoneNumber: "+18478468245",
    createdUserId: "",
    views: 35,
    createdAt: new Date(),
    category: "education",
    subcategory: "Образование",
  },
  {
    id: 10,
    isPremium: true,
    title: "Курсы программирования",
    description:
      "Обучающие курсы по программированию для начинающих и опытных разработчиков. Получите новые навыки и станьте востребованным специалистом!",
    state: "California",
    city: "Los Angeles",
    address: "456 Oak St",
    amount: 800,
    image: ["https://eva.osclass-pro.ru/oc-content/uploads/0/17_preview.jpg"],
    phoneNumber: "+18478468245",
    createdUserId: "",
    views: 53,
    createdAt: new Date(),
    category: "education",
    subcategory: "Образование",
  },
  {
    id: 11,
    isPremium: true,
    title: "Курсы фотографии",
    description:
      "Профессиональные курсы фотографии для всех уровней подготовки. Изучайте искусство фотографии у лучших мастеров своего дела!",
    state: "California",
    city: "Los Angeles",
    address: "101 Maple St",
    amount: 600,
    image: ["https://eva.osclass-pro.ru/oc-content/uploads/0/17_preview.jpg"],
    phoneNumber: "+18478468245",
    createdUserId: "",
    views: 47,
    createdAt: new Date(),
    category: "education",
    subcategory: "Образование",
  },
  {
    id: 12,
    isPremium: true,
    title: "Знакомства в вашем городе",
    description:
      "Новые знакомства и интересные встречи ждут вас! Присоединяйтесь к нашему сообществу и найдите свою вторую половинку прямо сейчас.",
    state: "California",
    city: "Los Angeles",
    address: "101 Maple St",
    amount: 0,
    image: ["https://eva.osclass-pro.ru/oc-content/uploads/0/17_preview.jpg"],
    phoneNumber: "+18478468245",
    createdUserId: "",
    views: 21,
    createdAt: new Date(),
    category: "dating",
    subcategory: "Знакомства",
  },
  {
    id: 13,
    isPremium: true,
    title: "Знакомства для серьезных отношений",
    description:
      "Ищете партнера для серьезных отношений? Присоединяйтесь к нашему сайту знакомств и найдите свою любовь!",
    state: "California",
    city: "Los Angeles",
    address: "456 Oak St",
    amount: 0,
    image: ["https://eva.osclass-pro.ru/oc-content/uploads/0/17_preview.jpg"],
    phoneNumber: "+18478468245",
    createdUserId: "",
    views: 12,
    createdAt: new Date(),
    category: "dating",
    subcategory: "Знакомства",
  },
  {
    id: 14,
    isPremium: true,
    title: "Онлайн знакомства",
    description:
      "Уникальная возможность познакомиться с интересными людьми прямо сейчас. Найдите свою вторую половинку без долгих поисков!",
    state: "California",
    city: "Los Angeles",
    address: "789 Elm St",
    amount: 0,
    image: ["https://eva.osclass-pro.ru/oc-content/uploads/0/17_preview.jpg"],
    phoneNumber: "+18478468245",
    createdUserId: "",
    views: 17,
    createdAt: new Date(),
    category: "dating",
    subcategory: "Знакомства",
  },
  {
    id: 15,
    isPremium: true,
    title: "Онлайн знакомства",
    description:
      "Уникальная возможность познакомиться с интересными людьми прямо сейчас. Найдите свою вторую половинку без долгих поисков!",
    state: "California",
    city: "Los Angeles",
    address: "789 Elm St",
    amount: 0,
    image: ["https://eva.osclass-pro.ru/oc-content/uploads/0/17_preview.jpg"],
    phoneNumber: "+18478468245",
    createdUserId: "",
    views: 17,
    createdAt: new Date(),
    category: "dating",
    subcategory: "Знакомства",
  },
];
